trigger:
- master
- release/*
- test-azure

jobs:
- job: Build
  variables:
    TZ: 'Europe/Oslo'
    WIN_TZ: 'W. Europe Standard Time'
    NODE_VERSION: 10.15.0
  strategy:
    matrix:
      linux_node_10_x:
        IMAGE_NAME: 'ubuntu-16.04'
      macOS_node_10_x:
        IMAGE_NAME: 'macos-10.13'
      win64_node_10_x:
        IMAGE_NAME: 'vs2017-win2016'
      win32_node_10_x:
        IMAGE_NAME: 'vs2017-win2016'
        NODE_ARCH: '32'

  pool:
    vmImage: $(IMAGE_NAME)
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    condition: ne(variables['NODE_ARCH'], '32')
    displayName: 'Install Node.js $(NODE_VERSION)'
  - bash: |
      choco install -y nvm
      export PATH=$NVM_HOME:$PATH
      nvm install $(NODE_VERSION) $(NODE_ARCH)
      nvm use $(NODE_VERSION) $(NODE_ARCH)
      ln -sf "$NVM_SYMLINK/node" "$NODE_SYMLINK/node"
    env: {
      NVM_HOME: "/C/ProgramData/nvm",
      NVM_SYMLINK: "/C/ProgramData/nvm/v$(NODE_VERSION)",
      NODE_SYMLINK: "/C/Program Files/nodejs",
    }
    condition: and(contains(variables['IMAGE_NAME'], 'win'), eq(variables['NODE_ARCH'], '32'))
    displayName: 'Install Node.js $(NODE_VERSION) 32-bit'
  - script: |
      npm i
      npm run build
      npm run test
    displayName: 'Build'
  - script: |
      sudo apt-get update
      sudo apt-get install icnsutils
    condition: contains(variables['IMAGE_NAME'], 'ubuntu')
  - script: |
      npm run release
    env: {
      GH_TOKEN: $(wayland_github_token)
    }
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: 'Release'

